// <auto-generated />
using System;
using APIBLOG.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIBLOG.Migrations
{
    [DbContext(typeof(ApiblogContext))]
    partial class ApiblogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIBLOG.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCategoria")
                        .HasName("PK__CATEGORI__A3C02A1086117A8A");

                    b.ToTable("CATEGORIA", (string)null);
                });

            modelBuilder.Entity("APIBLOG.Models.Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComentario"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contenido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdPost")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdComentario")
                        .HasName("PK__COMENTAR__DDBEFBF9A4E0BB96");

                    b.HasIndex("IdPost");

                    b.HasIndex("IdUsuario");

                    b.ToTable("COMENTARIO", (string)null);
                });

            modelBuilder.Entity("APIBLOG.Models.HistorialRefreshToken", b =>
                {
                    b.Property<int>("IdHistorialToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorialToken"));

                    b.Property<bool?>("EsActivo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit")
                        .HasComputedColumnSql("(case when [FechaExpiracion]<getdate() then CONVERT([bit],(0)) else CONVERT([bit],(1)) end)", false);

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHistorialToken")
                        .HasName("PK__HISTORIA__03DC48A56DB735F0");

                    b.HasIndex("IdUsuario");

                    b.ToTable("HISTORIAL_REFRESH_TOKEN", (string)null);
                });

            modelBuilder.Entity("APIBLOG.Models.Post", b =>
                {
                    b.Property<int>("IdPost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPost"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contenido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPost")
                        .HasName("PK__POST__F8DCBD4D44C192C8");

                    b.HasIndex("IdUsuario");

                    b.ToTable("POST", (string)null);
                });

            modelBuilder.Entity("APIBLOG.Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contraseña")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario");

                    b.HasKey("IdUsuario")
                        .HasName("PK__USUARIO__5B65BF978CD2A107");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("PostCategorium", b =>
                {
                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdPost")
                        .HasColumnType("int");

                    b.HasKey("IdCategoria", "IdPost")
                        .HasName("PK__POST_CAT__6C4DE1C4DCBE7F07");

                    b.HasIndex("IdPost");

                    b.ToTable("POST_CATEGORIA", (string)null);
                });

            modelBuilder.Entity("APIBLOG.Models.Comentario", b =>
                {
                    b.HasOne("APIBLOG.Models.Post", "IdPostNavigation")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdPost")
                        .HasConstraintName("FK__COMENTARI__IdPos__656C112C");

                    b.HasOne("APIBLOG.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__COMENTARI__IdUsu__6477ECF3");

                    b.Navigation("IdPostNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("APIBLOG.Models.HistorialRefreshToken", b =>
                {
                    b.HasOne("APIBLOG.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("HistorialRefreshTokens")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__HISTORIAL__IdUsu__6FE99F9F");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("APIBLOG.Models.Post", b =>
                {
                    b.HasOne("APIBLOG.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Posts")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__POST__IdUsuario__619B8048");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("PostCategorium", b =>
                {
                    b.HasOne("APIBLOG.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK__POST_CATE__IdCat__68487DD7");

                    b.HasOne("APIBLOG.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("IdPost")
                        .IsRequired()
                        .HasConstraintName("FK__POST_CATE__IdPos__693CA210");
                });

            modelBuilder.Entity("APIBLOG.Models.Post", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("APIBLOG.Models.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("HistorialRefreshTokens");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
